version: "3.2"

services:
  riverdiver-web-app:
    build:
      context: ./
      dockerfile: ./containers/webapp/Dockerfile
    ports:
      - 8080:8080
    environment:
      - "RD_PORT=8080"
      - "RD_SENDGRID_KEY=setme"
      - "RD_WAIVER_TO_EMAIL=recipient@example.com"
      - "RD_WAIVER_FROM_EMAIL=noreply@example.com"